{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-common",
    "version": "flux-1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-1.3.jar",
          "url": "central-common-flux-1.3.jar",
          "size": 220681,
          "sha512": "24a639f262910094a56b6ff3b9a2fb2645f2e2c8c1cf126df843abff4f7823fb93a2b9b4667f49ec50d796d9bd8f38e6142bcbe112781ca35ba6d716c01a125e",
          "sha256": "29cab9bef624a8adb34c90d463096ce22cf13411e9914cca89fe72dda974cea1",
          "sha1": "4159b25428296ad354f4f50646aa0bba9c7313fc",
          "md5": "c427ee598faeec7fd4af3716c06d01db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-1.3.jar",
          "url": "central-common-flux-1.3.jar",
          "size": 220681,
          "sha512": "24a639f262910094a56b6ff3b9a2fb2645f2e2c8c1cf126df843abff4f7823fb93a2b9b4667f49ec50d796d9bd8f38e6142bcbe112781ca35ba6d716c01a125e",
          "sha256": "29cab9bef624a8adb34c90d463096ce22cf13411e9914cca89fe72dda974cea1",
          "sha1": "4159b25428296ad354f4f50646aa0bba9c7313fc",
          "md5": "c427ee598faeec7fd4af3716c06d01db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-common-flux-1.3-sources.jar",
          "url": "central-common-flux-1.3-sources.jar",
          "size": 54408,
          "sha512": "b41d7a27cc79bb3dbb2af2534e5cb2db4f0c00729a2b58a809c545d09e92679f14fde772d8914cbd2509f21a3141979246d8297aa2d1b04e839e4c3b34c1999d",
          "sha256": "7d4b8a86de3c086854a8e64edd131593390a74cd540470ae595652a2565cb2ad",
          "sha1": "e625b8c424e633e8c165a766142d12c9480a6093",
          "md5": "f453727f348552955b5709b6827bbf78"
        }
      ]
    }
  ]
}
