{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-common",
    "version": "flux-3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-3.0.6.jar",
          "url": "central-common-flux-3.0.6.jar",
          "size": 356196,
          "sha512": "ecdd599f5971097d0247cea0559804e857d90fd5f23de6de949d57d0827c775f2d602e80a62a88b9e7cd239276e1bbbda83307dfd0e910cbf5052cecc906e470",
          "sha256": "17d728b04de6276844011ec796bec3851bdb2e10b20190bd325b2219353208ad",
          "sha1": "27df5f2f4af868ac35bf0e31024c38a3a6c1634b",
          "md5": "47edd0f6733de18417f3d117f3466648"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.mkammerer",
          "module": "argon2-jvm",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "at.favre.lib",
          "module": "bcrypt",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-3.0.6.jar",
          "url": "central-common-flux-3.0.6.jar",
          "size": 356196,
          "sha512": "ecdd599f5971097d0247cea0559804e857d90fd5f23de6de949d57d0827c775f2d602e80a62a88b9e7cd239276e1bbbda83307dfd0e910cbf5052cecc906e470",
          "sha256": "17d728b04de6276844011ec796bec3851bdb2e10b20190bd325b2219353208ad",
          "sha1": "27df5f2f4af868ac35bf0e31024c38a3a6c1634b",
          "md5": "47edd0f6733de18417f3d117f3466648"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-common-flux-3.0.6-sources.jar",
          "url": "central-common-flux-3.0.6-sources.jar",
          "size": 101648,
          "sha512": "99aa37dd1f08a80e9fd3d9cf439cd20a3ca1e75f7278818af889a844b0c289c7c8e53d04438de7e3f29e38992870ea296b112e4f2b8d5dc57d37610755765caf",
          "sha256": "9a9e9e452c43a15e6c0ab51e8ab958ef8a2ada6928163f3274d6069d00e4a74e",
          "sha1": "4f91f552bd9db47d2b6ca3821673f5bd0c709aea",
          "md5": "7d62b33ed777aec8e5231cd72f052486"
        }
      ]
    }
  ]
}
