{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-worldlink",
    "version": "flux-3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.3.jar",
          "url": "central-worldlink-flux-3.0.3.jar",
          "size": 222845,
          "sha512": "51e2e626bf5b441f8f24e0e1aeb385c21efc989266ba36e9ce8b51ff77f76d7b12cdcf6048f84db381bd2d48ea6899281f4c5d4c31ffef4da5e20491684920bd",
          "sha256": "f4e948ad729d57aba8a7320ad6ea5502587f6a105b4cddc7805d5d8ae0734c59",
          "sha1": "b1dbd48899bbd40b04a0e3ca05857a2195c8f8d6",
          "md5": "f3fd79ec248a387d1db8f104a5dd0d71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.3.jar",
          "url": "central-worldlink-flux-3.0.3.jar",
          "size": 222845,
          "sha512": "51e2e626bf5b441f8f24e0e1aeb385c21efc989266ba36e9ce8b51ff77f76d7b12cdcf6048f84db381bd2d48ea6899281f4c5d4c31ffef4da5e20491684920bd",
          "sha256": "f4e948ad729d57aba8a7320ad6ea5502587f6a105b4cddc7805d5d8ae0734c59",
          "sha1": "b1dbd48899bbd40b04a0e3ca05857a2195c8f8d6",
          "md5": "f3fd79ec248a387d1db8f104a5dd0d71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-worldlink-flux-3.0.3-sources.jar",
          "url": "central-worldlink-flux-3.0.3-sources.jar",
          "size": 37262,
          "sha512": "c7a53981893e2f611de63529a5ef19ab3a4f3f1dfb9594d328fa9403f94d0867ef04cceba1aaf80ca7557df530aa0b964c35a71d495293a8e26a6842208f6e42",
          "sha256": "98eecd58d3deb34329a538d95a77687638fa83c4f912d3568f95e59cab193a72",
          "sha1": "73bb722e9403d2369a423f3706e6ceaaf3b0efd5",
          "md5": "bedae1b65cd1a9efc41175489369e636"
        }
      ]
    }
  ]
}
