{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "openrune-central",
    "version": "flux-3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-flux-3.0.2.jar",
          "url": "openrune-central-flux-3.0.2.jar",
          "size": 359089,
          "sha512": "f0812fc09e7c9953839bce3e72db70f1e11261cbc9cad2fbb98b053c7eab720ab3668f5cf5625bf5f32f5af2b6adcfddd13ac5cd60d4d3c494282f23f5b2a136",
          "sha256": "f4580cc242bbacebfcf26757403d695557818ffe5c2161b5628ccdd98aab13a5",
          "sha1": "e1b3e39b1e973b35a69e4273e701d4315dd32c0b",
          "md5": "a9b92532af58bd5cabbe2672025aa2e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "central-worldlink",
          "version": {
            "requires": "flux-3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-forwarded-header"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-yaml",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-ktor",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-logger-slf4j",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-flux-3.0.2.jar",
          "url": "openrune-central-flux-3.0.2.jar",
          "size": 359089,
          "sha512": "f0812fc09e7c9953839bce3e72db70f1e11261cbc9cad2fbb98b053c7eab720ab3668f5cf5625bf5f32f5af2b6adcfddd13ac5cd60d4d3c494282f23f5b2a136",
          "sha256": "f4580cc242bbacebfcf26757403d695557818ffe5c2161b5628ccdd98aab13a5",
          "sha1": "e1b3e39b1e973b35a69e4273e701d4315dd32c0b",
          "md5": "a9b92532af58bd5cabbe2672025aa2e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-flux-3.0.2-sources.jar",
          "url": "openrune-central-flux-3.0.2-sources.jar",
          "size": 71352,
          "sha512": "27a3da57bf1e2d2e5163b685cf72826935a8334f40311834957844a898fe8e1f3e69a8ab797fd26783ea0ecababe5118f85b544c8943474d11b5a7e1a1af18ff",
          "sha256": "b9a8c5926482c8df5dc0f3d8e7e4f5976340de0213cb3e3a3310983fdc4aab91",
          "sha1": "2d9d29d311f93fd2fbcaacf06d3742827aebf141",
          "md5": "0a931f8ae196ae38827421e7a3530bea"
        }
      ]
    }
  ]
}
