{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-server",
    "version": "flux-1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-server-flux-1.4.2.jar",
          "url": "central-server-flux-1.4.2.jar",
          "size": 420706,
          "sha512": "5afabbbb5285ce079237b66764edb9828673241df418fe867ffa73a1a1183f50ab32ced088464e274b0542faef1858496a301bc1b7c876d185b836f4a8d575d9",
          "sha256": "51191ccfc08ffd525ddb241c55ac0382eb244483309bff1ff0e880efde66f054",
          "sha1": "b2b1aac8bd93e0f2fc06c70642739fe955c827d9",
          "md5": "67629716349420bbd91cb92ceea855e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-forwarded-header"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "at.favre.lib",
          "module": "bcrypt",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-server-flux-1.4.2.jar",
          "url": "central-server-flux-1.4.2.jar",
          "size": 420706,
          "sha512": "5afabbbb5285ce079237b66764edb9828673241df418fe867ffa73a1a1183f50ab32ced088464e274b0542faef1858496a301bc1b7c876d185b836f4a8d575d9",
          "sha256": "51191ccfc08ffd525ddb241c55ac0382eb244483309bff1ff0e880efde66f054",
          "sha1": "b2b1aac8bd93e0f2fc06c70642739fe955c827d9",
          "md5": "67629716349420bbd91cb92ceea855e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-server-flux-1.4.2-sources.jar",
          "url": "central-server-flux-1.4.2-sources.jar",
          "size": 86258,
          "sha512": "b85b01c572c80bec1d96e279dcd9ac0e802490c941ae83be319f16908a3780cc2dd940d2248188709c7b527449d8b1b5c41558f7a2a1576dd20b9d932f333a13",
          "sha256": "02aef3d68247d554c8d2af74905e819baad3b6f63e61d628c4bffe1efb659bda",
          "sha1": "367ad28b65341dcd518cae6e51f257405b4a7319",
          "md5": "ec46ee3278092293a2bdb7eebe55ec1e"
        }
      ]
    }
  ]
}
