{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-worldlink",
    "version": "flux-3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.0.jar",
          "url": "central-worldlink-flux-3.0.0.jar",
          "size": 187755,
          "sha512": "be9f42fb327c3b64a7faac21e5a0b67bc4391c8a06f9a76c4d5fbc3cdde3af10e6905aa410f5ed00a722d69d4af9fcc7d7753e3d27eee2102476635cc2faa0bd",
          "sha256": "5f155c8ecd1eb724eea471df2affd1313181b8367962731d40af8406c45b65ae",
          "sha1": "251dea0385a4c4558a30053df85da4f17fe523fe",
          "md5": "531410c92c2bfd0c8ed1f11cad78d363"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.0.jar",
          "url": "central-worldlink-flux-3.0.0.jar",
          "size": 187755,
          "sha512": "be9f42fb327c3b64a7faac21e5a0b67bc4391c8a06f9a76c4d5fbc3cdde3af10e6905aa410f5ed00a722d69d4af9fcc7d7753e3d27eee2102476635cc2faa0bd",
          "sha256": "5f155c8ecd1eb724eea471df2affd1313181b8367962731d40af8406c45b65ae",
          "sha1": "251dea0385a4c4558a30053df85da4f17fe523fe",
          "md5": "531410c92c2bfd0c8ed1f11cad78d363"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-worldlink-flux-3.0.0-sources.jar",
          "url": "central-worldlink-flux-3.0.0-sources.jar",
          "size": 30432,
          "sha512": "b1e5b472ea1b39345cad0493d18177005bea3d378bf50940f8540e638ae7fe4a9ddcce01dbba06a8857f4a96fa1d4189519972eafd3508ee373ee476b30d6fcd",
          "sha256": "6865b9fa3ff0c22949df926001b01757912e2e18d9201e797c2d6ec4ac31bced",
          "sha1": "01b392fa24198a7ef32e071d563a4fb540405968",
          "md5": "eead9f9f73a5b5707c8e3a236e7e8066"
        }
      ]
    }
  ]
}
