{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "openrune-central",
    "version": "flux-3.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-flux-3.0.8.jar",
          "url": "openrune-central-flux-3.0.8.jar",
          "size": 431410,
          "sha512": "6fee3dee063dcc3bdde681cf7a80f14a1e43435f06fd1bd4c14809685a0c4cb62239a8ec6138092196ed1e8d75007fb31235ee116009e6913bd28350419cfeb7",
          "sha256": "f07da7b39eb50afa0ea3daf7156a27bd686cedb4baa7e51a145f4ab0c1cef13d",
          "sha1": "fee12378a68e8aab8fe1663fa3c82d69ccf67c16",
          "md5": "2cde2be24649de735aba8ef955380ab5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.8"
          }
        },
        {
          "group": "dev.or2",
          "module": "central-worldlink",
          "version": {
            "requires": "flux-3.0.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-forwarded-header"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-yaml",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-ktor",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-logger-slf4j",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-flux-3.0.8.jar",
          "url": "openrune-central-flux-3.0.8.jar",
          "size": 431410,
          "sha512": "6fee3dee063dcc3bdde681cf7a80f14a1e43435f06fd1bd4c14809685a0c4cb62239a8ec6138092196ed1e8d75007fb31235ee116009e6913bd28350419cfeb7",
          "sha256": "f07da7b39eb50afa0ea3daf7156a27bd686cedb4baa7e51a145f4ab0c1cef13d",
          "sha1": "fee12378a68e8aab8fe1663fa3c82d69ccf67c16",
          "md5": "2cde2be24649de735aba8ef955380ab5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-flux-3.0.8-sources.jar",
          "url": "openrune-central-flux-3.0.8-sources.jar",
          "size": 82647,
          "sha512": "90632f4f7f2ec20918016f71ef64e14f6a3049b708dafbfa27538b19842c6b58d1e95349a7829cfe20329abf5c6519ec4ec738373402fd893cf35c88c5e91a1c",
          "sha256": "15f048ebaccbb2e93a2c8a47f8b019b4dc0bce31733cbe664efd9a77dde4fa97",
          "sha1": "002b5533c00fef823eca1653206232fe7b8d5657",
          "md5": "df1947cb2f5a2829b5d83a8660b5074b"
        }
      ]
    }
  ]
}
