{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-worldlink",
    "version": "flux-3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.5.jar",
          "url": "central-worldlink-flux-3.0.5.jar",
          "size": 222845,
          "sha512": "0a496dd9dbd1126cd74a99e020fb4fdf4baae51e1d54da296c22497948162034ccf0709cb316e41fc4e48c4fe8ffd2991e8905bb0764cb8aad7f173b5290848d",
          "sha256": "5bdccf275ea0d6fb79db9ed2187df7a2d1daedb949521ce5d7d762d8b3c17abb",
          "sha1": "84b2edb72823a1be0eaa23281ba08ed070cb4bd2",
          "md5": "a2e304f1cb2be890d475fa07d82cfb0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.5.jar",
          "url": "central-worldlink-flux-3.0.5.jar",
          "size": 222845,
          "sha512": "0a496dd9dbd1126cd74a99e020fb4fdf4baae51e1d54da296c22497948162034ccf0709cb316e41fc4e48c4fe8ffd2991e8905bb0764cb8aad7f173b5290848d",
          "sha256": "5bdccf275ea0d6fb79db9ed2187df7a2d1daedb949521ce5d7d762d8b3c17abb",
          "sha1": "84b2edb72823a1be0eaa23281ba08ed070cb4bd2",
          "md5": "a2e304f1cb2be890d475fa07d82cfb0f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-worldlink-flux-3.0.5-sources.jar",
          "url": "central-worldlink-flux-3.0.5-sources.jar",
          "size": 37262,
          "sha512": "e62e6c27fb0d6d5ccfcf60cc39dd4c1919499cc64907aa37f1ff8ee469d2c7db070095038c84a842f8aca7cc99e03881d401b33fa3694b1c60967d229aafaddd",
          "sha256": "6b01a73bfa92263001b80711b009173272c097d4024a2a132bb0b640c93569f0",
          "sha1": "9488f28c70ab19c3c8bde24f5c58827e744e1c8c",
          "md5": "6bc6706827e1a41630103a593aabdbd4"
        }
      ]
    }
  ]
}
