{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-worldlink",
    "version": "flux-3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.5.jar",
          "url": "central-worldlink-flux-3.0.5.jar",
          "size": 222845,
          "sha512": "18b7bf2b0503cf8a00459fbb25d038b1a78d90c7d671f84effdc1136e3e21f2d839d13f5a9cafabe436e690a9d711b2595adc40ca9dbe116c8660dacc332d5fc",
          "sha256": "0bf4811a98d3749b3107cee0795bbeef4b25690865d81fe79e2fa93b8db0bdb9",
          "sha1": "590358cb515e9d365566acd8acfe71e3501d7855",
          "md5": "1065eb873e7a8bb72549f72f9f1c7840"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.5.jar",
          "url": "central-worldlink-flux-3.0.5.jar",
          "size": 222845,
          "sha512": "18b7bf2b0503cf8a00459fbb25d038b1a78d90c7d671f84effdc1136e3e21f2d839d13f5a9cafabe436e690a9d711b2595adc40ca9dbe116c8660dacc332d5fc",
          "sha256": "0bf4811a98d3749b3107cee0795bbeef4b25690865d81fe79e2fa93b8db0bdb9",
          "sha1": "590358cb515e9d365566acd8acfe71e3501d7855",
          "md5": "1065eb873e7a8bb72549f72f9f1c7840"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-worldlink-flux-3.0.5-sources.jar",
          "url": "central-worldlink-flux-3.0.5-sources.jar",
          "size": 37313,
          "sha512": "347860861006c0b05807d2f28a7721dc0d371312b08f190b4a53d768bddccd30fdf1d85c713b926dbf414445762944c6dc4add73fd97bff50a13316787dbfda0",
          "sha256": "7d1827012c4af33e8d760910ed0b98d5844fb3e505ff104a3d0188ab68bbf227",
          "sha1": "2d70078d2d518b95c8263068702db64642e21b86",
          "md5": "fdd5b6e5863504efee268dbafd8d1fe3"
        }
      ]
    }
  ]
}
