{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-server",
    "version": "flux-1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-server-flux-1.4.3.jar",
          "url": "central-server-flux-1.4.3.jar",
          "size": 454512,
          "sha512": "63c4d1390a94a50b05544a3dcef4de607f74711fb31628b3eabe255cf84cda02046fa8f35d2297059db45376a6148e4372d28518ad08a0299d6799569a332d1a",
          "sha256": "4579ce2d90afe0de8efcb34b36add27040c8f027b1d46d93f257e7220340d816",
          "sha1": "f2ffaac551b8280a84ae118268def96705141122",
          "md5": "8a3c9d4d9ccbb194bf55c1d961d26604"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-1.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-forwarded-header"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "at.favre.lib",
          "module": "bcrypt",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-server-flux-1.4.3.jar",
          "url": "central-server-flux-1.4.3.jar",
          "size": 454512,
          "sha512": "63c4d1390a94a50b05544a3dcef4de607f74711fb31628b3eabe255cf84cda02046fa8f35d2297059db45376a6148e4372d28518ad08a0299d6799569a332d1a",
          "sha256": "4579ce2d90afe0de8efcb34b36add27040c8f027b1d46d93f257e7220340d816",
          "sha1": "f2ffaac551b8280a84ae118268def96705141122",
          "md5": "8a3c9d4d9ccbb194bf55c1d961d26604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-server-flux-1.4.3-sources.jar",
          "url": "central-server-flux-1.4.3-sources.jar",
          "size": 92989,
          "sha512": "dfbff07a1312127b072967b7761f9fa873e9da6712d7a2018268213e013b53262bc03c24686a7ff5b539186fa82c41bb7c6c7ca3120e6990eed6f9fca734c08b",
          "sha256": "17403ec367ff5d802e2748a6798da525c15e2c7091e12c662593753d14205804",
          "sha1": "1b63fcc01a451700583d3b2fdfcaef2bd1b623fb",
          "md5": "e3592248588b54f6d5572fbc51e3b30f"
        }
      ]
    }
  ]
}
