{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-common",
    "version": "flux-3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-3.0.1.jar",
          "url": "central-common-flux-3.0.1.jar",
          "size": 281465,
          "sha512": "7c8027ca0a3460fee24b5cedd8efe5a31ab3077f80dc5e426caf173e197c3352e7e0d9560d9295bae57aa7918ce774b1e546f923d811fdebcc57e2513606c988",
          "sha256": "a18ea5c4239312c09e5e8799cc27f46a1b068fdfee2141a2ea3b3332fde5a779",
          "sha1": "c0fb58fc28398642670a9851a49af4f9069b383d",
          "md5": "2f762ab7f77fc70bec85daa5a70cb1e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.mkammerer",
          "module": "argon2-jvm",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "at.favre.lib",
          "module": "bcrypt",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-3.0.1.jar",
          "url": "central-common-flux-3.0.1.jar",
          "size": 281465,
          "sha512": "7c8027ca0a3460fee24b5cedd8efe5a31ab3077f80dc5e426caf173e197c3352e7e0d9560d9295bae57aa7918ce774b1e546f923d811fdebcc57e2513606c988",
          "sha256": "a18ea5c4239312c09e5e8799cc27f46a1b068fdfee2141a2ea3b3332fde5a779",
          "sha1": "c0fb58fc28398642670a9851a49af4f9069b383d",
          "md5": "2f762ab7f77fc70bec85daa5a70cb1e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-common-flux-3.0.1-sources.jar",
          "url": "central-common-flux-3.0.1-sources.jar",
          "size": 65787,
          "sha512": "2a09ab385964854e2e3573440fe7e008289231fe83b488681586d74c98a51513a433562e2a38102eb11d05abb8f9cecab2cac03a5d94976f2ec6e505f4651a14",
          "sha256": "17b392efa0a967b024575c1b4b9f4b04811e244c141c92e1a0e44491e9ccf878",
          "sha1": "114c2835314a9b1a98105ba6c590d20b628cb294",
          "md5": "9c7a5552c9302e4c9d7da80429970916"
        }
      ]
    }
  ]
}
