{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "openrune-central",
    "version": "flux-3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-flux-3.0.0.jar",
          "url": "openrune-central-flux-3.0.0.jar",
          "size": 345568,
          "sha512": "787ab42f945c3d0891a000c5ad3afeaf147264fb5891ed51e4e1c54fa8145d8da7ef8f1c06f2f148556ffd1f05997b11176af4913b321b35996211e9f74bf413",
          "sha256": "847d79c08f13d25ab8ca61f87f0bd33e4e98ddffe2a430dfb016dab5814fb072",
          "sha1": "a35d35f0ca79466e11e2a322dbd220d5f4114b2c",
          "md5": "72cd8fdc19f6e551d2e80e0b0d33133f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "central-worldlink",
          "version": {
            "requires": "flux-3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-forwarded-header"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-yaml",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-ktor",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-logger-slf4j",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-flux-3.0.0.jar",
          "url": "openrune-central-flux-3.0.0.jar",
          "size": 345568,
          "sha512": "787ab42f945c3d0891a000c5ad3afeaf147264fb5891ed51e4e1c54fa8145d8da7ef8f1c06f2f148556ffd1f05997b11176af4913b321b35996211e9f74bf413",
          "sha256": "847d79c08f13d25ab8ca61f87f0bd33e4e98ddffe2a430dfb016dab5814fb072",
          "sha1": "a35d35f0ca79466e11e2a322dbd220d5f4114b2c",
          "md5": "72cd8fdc19f6e551d2e80e0b0d33133f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-flux-3.0.0-sources.jar",
          "url": "openrune-central-flux-3.0.0-sources.jar",
          "size": 67612,
          "sha512": "dfc67065c172993a7b7fb17964ebfdbfb62d9643d9c82033b750b27fee365e71e0276b3c4c29a5d2a088dc900960237a6f658c02d1aa717ac9c2ca5c26f7d93e",
          "sha256": "3643f02e29fdf12d4a7c77231c6e14eeb8d0980f78f5f3ca86100859282cce78",
          "sha1": "141090fa7f245c47638277a46b9ff4f5015bf7c9",
          "md5": "fedc66eb3ff1dffe9736dcaec7abd57a"
        }
      ]
    }
  ]
}
