{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-common",
    "version": "flux-3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-3.0.4.jar",
          "url": "central-common-flux-3.0.4.jar",
          "size": 330543,
          "sha512": "a932046cd85ad40619d870e459242ef34cef426e8be0269f317b2835faad12fd4e5a70b7e10da3771f4643ca37bf185f9b4a9beb46c3694656a399d5c3a1df51",
          "sha256": "cfc5bc249dffc2994c554edbd57974f2b6119eb917ab2fbca8029951e44a6d6c",
          "sha1": "9f12d2d297caec6c82bf6615115ebb0c0a914d8e",
          "md5": "b035f0f2ec1c381a3cd1433f1cfd9664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.mkammerer",
          "module": "argon2-jvm",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "at.favre.lib",
          "module": "bcrypt",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-3.0.4.jar",
          "url": "central-common-flux-3.0.4.jar",
          "size": 330543,
          "sha512": "a932046cd85ad40619d870e459242ef34cef426e8be0269f317b2835faad12fd4e5a70b7e10da3771f4643ca37bf185f9b4a9beb46c3694656a399d5c3a1df51",
          "sha256": "cfc5bc249dffc2994c554edbd57974f2b6119eb917ab2fbca8029951e44a6d6c",
          "sha1": "9f12d2d297caec6c82bf6615115ebb0c0a914d8e",
          "md5": "b035f0f2ec1c381a3cd1433f1cfd9664"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-common-flux-3.0.4-sources.jar",
          "url": "central-common-flux-3.0.4-sources.jar",
          "size": 92157,
          "sha512": "9278ff291b21bf8181c1c2c369e19378a018c1e0fcaa044dcb621e8ea3ed98ff51e2a5c1c4a055f4f77d91bd70a17f0a7bf2865a696867e92f1c4635da8b12c9",
          "sha256": "b1a7af92cfe0a3499128f2be64e51406dfd1da06f82d5282dce66d33a2937c1c",
          "sha1": "1f463bf2b9f2123369830a46687cecc3195252c4",
          "md5": "46147f57eecc9ac2a131a43a109c5868"
        }
      ]
    }
  ]
}
