{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-common",
    "version": "flux-3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-3.0.5.jar",
          "url": "central-common-flux-3.0.5.jar",
          "size": 339293,
          "sha512": "c9580c1c7fa1ae197071c6c32d1c3714e565cf67a9b4514beb9e47db9c7d860eb3241aa87316fb54b74cde442735ba94fad915d6347f93767542ba23aa94e196",
          "sha256": "aa78edebfe6aeee29ac4b70ce17ce1d123f3a6cfef40da167a9e93bbba9fdf31",
          "sha1": "d58ca1bed910c4855f5919b313399807fcc1473b",
          "md5": "43cbe1943f7b04d759bde1b09778b541"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.mkammerer",
          "module": "argon2-jvm",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "at.favre.lib",
          "module": "bcrypt",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-flux-3.0.5.jar",
          "url": "central-common-flux-3.0.5.jar",
          "size": 339293,
          "sha512": "c9580c1c7fa1ae197071c6c32d1c3714e565cf67a9b4514beb9e47db9c7d860eb3241aa87316fb54b74cde442735ba94fad915d6347f93767542ba23aa94e196",
          "sha256": "aa78edebfe6aeee29ac4b70ce17ce1d123f3a6cfef40da167a9e93bbba9fdf31",
          "sha1": "d58ca1bed910c4855f5919b313399807fcc1473b",
          "md5": "43cbe1943f7b04d759bde1b09778b541"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-common-flux-3.0.5-sources.jar",
          "url": "central-common-flux-3.0.5-sources.jar",
          "size": 95207,
          "sha512": "ec9bc3ee6e50f81875cf0df8fe797aeb64bbf11144d7f04d01502e203dd712718cf648f809a4d3b8f5fda9318e8523daba1bbaf0f0c75e33b1d691bebeb002d6",
          "sha256": "56aec597d794c32424584eea1b7e552103f95d6a9bce500d2be923c2372f436d",
          "sha1": "08fefa482b24d933995c86d03965d8260dc8f80d",
          "md5": "6e1790ca85200b2de19d36dcdbac2212"
        }
      ]
    }
  ]
}
