{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-worldlink",
    "version": "flux-3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.1.jar",
          "url": "central-worldlink-flux-3.0.1.jar",
          "size": 187755,
          "sha512": "129c7d265bd6f487d3bf654c3177b49ffe2277fcda27ddcb9951fe69822cd22b9d45df5714cac49ef20895f7dc14a7743fb378ff6486b6b0dc8a48f653ac8f99",
          "sha256": "433ae71b2276a121f40b0d5eb5b9e1060859b61f53b8a3fdf972a3a0e37e2508",
          "sha1": "73b80a8b0812074be709b343474a02cdb0d21caf",
          "md5": "e7e5dc6a75cbf7396d16da80161919bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "flux-3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-flux-3.0.1.jar",
          "url": "central-worldlink-flux-3.0.1.jar",
          "size": 187755,
          "sha512": "129c7d265bd6f487d3bf654c3177b49ffe2277fcda27ddcb9951fe69822cd22b9d45df5714cac49ef20895f7dc14a7743fb378ff6486b6b0dc8a48f653ac8f99",
          "sha256": "433ae71b2276a121f40b0d5eb5b9e1060859b61f53b8a3fdf972a3a0e37e2508",
          "sha1": "73b80a8b0812074be709b343474a02cdb0d21caf",
          "md5": "e7e5dc6a75cbf7396d16da80161919bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-worldlink-flux-3.0.1-sources.jar",
          "url": "central-worldlink-flux-3.0.1-sources.jar",
          "size": 30432,
          "sha512": "77b5420420240de18a993089427131436a8ccc6192c210fa2d1d42fc65372193cdc31da254bb80b85cd240c01e5b6af63b9398a5d08926208ca464030f9f3cfc",
          "sha256": "29bdfb4c785ea3dce92b2e7674b17662c427c4746a3c1a3abb92e05548806161",
          "sha1": "84f4197e4dcf33b109541cb3833584f1391c8477",
          "md5": "860f3724d9620e24bde307509904e84b"
        }
      ]
    }
  ]
}
